### ISSUE TITLE
formidable version issu

### ISSUE THREAD

**Issue by HaoJie23** [ofpay/nimg#5]
500 Error: Buffer.write(string, encoding, offset[, length]) is no longer supported
at Buffer.write (buffer.js:753:11)
at MultipartParser.initWithBoundary (/home/img/nimg-master/node_modules/connect/node_modules/formidable/lib/multipart_parser.js:61:17)
at IncomingForm._initMultipart (/home/img/nimg-master/node_modules/connect/node_modules/formidable/lib/incoming_form.js:308:10)
at IncomingForm._parseContentType (/home/img/nimg-master/node_modules/connect/node_modules/formidable/lib/incoming_form.js:250:12)
at IncomingForm.writeHeaders (/home/img/nimg-master/node_modules/connect/node_modules/formidable/lib/incoming_form.js:129:8)
at IncomingForm.parse (/home/img/nimg-master/node_modules/connect/node_modules/formidable/lib/incoming_form.js:97:8)
at /home/img/nimg-master/node_modules/connect/lib/middleware/multipart.js:125:12
at noop (/home/img/nimg-master/node_modules/connect/lib/middleware/multipart.js:22:3)
at multipart (/home/img/nimg-master/node_modules/connect/lib/middleware/multipart.js:76:5)
at /home/img/nimg-master/node_modules/connect/lib/middleware/bodyParser.js:57:9

nodejs v7.6.0
npm 4.1.2
Version: ImageMagick 7.0.5-0 Q16
Python 2.6.6

How can I fix it, can you tell me,please.

**Comment by freeman983** [comment]
Please see: [https://github.com/felixge/node-formidable/issues/364](url)
