### ISSUE TITLE
Error: Buffer.write(string, encoding, offset[, length]) is no longer supported

### ISSUE THREAD

**Issue by zhangwonderful** [ofpay/nimg#6]
我在nodejs 6.9.5环境下启动正常，上传文件就报这个错误
at Buffer.write (buffer.js:732:11)
at MultipartParser.initWithBoundary (/opt/nimg-master/node_modules/formidable/lib/multipart_parser.js:61:17)
at IncomingForm._initMultipart (/opt/nimg-master/node_modules/formidable/lib/incoming_form.js:308:10)
at IncomingForm._parseContentType (/opt/nimg-master/node_modules/formidable/lib/incoming_form.js:250:12)
at IncomingForm.writeHeaders (/opt/nimg-master/node_modules/formidable/lib/incoming_form.js:129:8)
at IncomingForm.parse (/opt/nimg-master/node_modules/formidable/lib/incoming_form.js:97:8)
at /opt/nimg-master/node_modules/connect/lib/middleware/multipart.js:125:12
at noop (/opt/nimg-master/node_modules/connect/lib/middleware/multipart.js:22:3)
at multipart (/opt/nimg-master/node_modules/connect/lib/middleware/multipart.js:76:5)
at /opt/nimg-master/node_modules/connect/lib/middleware/bodyParser.js:57:9

**Comment by yangy4444** [comment]
package.json 里边 改下express版本， "express": "3.21.2"
